-INCDIR $tb_dir/uvme  
-INCDIR $tb_dir
$tb_dir/define_lib.svh
$proj_dir/RTL/CORE/RTL_SOURCE_FILES/CORE_RTL/zilla_define.sv
$proj_dir/RTL/CORE/RTL_SOURCE_FILES/CORE_RTL/zilla_core_top.sv
$proj_dir/RTL/CORE/RTL_SOURCE_FILES/CORE_RTL/zilla_alu.sv
$proj_dir/RTL/CORE/RTL_SOURCE_FILES/CORE_RTL/zilla_branch_condition_check.sv
$proj_dir/RTL/CORE/RTL_SOURCE_FILES/CORE_RTL/zilla_data_mem_if.sv
$proj_dir/RTL/CORE/RTL_SOURCE_FILES/CORE_RTL/zilla_forwarding_unit.sv
$proj_dir/RTL/CORE/RTL_SOURCE_FILES/CORE_RTL/zilla_gpr.sv
$proj_dir/RTL/CORE/RTL_SOURCE_FILES/CORE_RTL/zilla_instruction_decoder.sv
$proj_dir/RTL/CORE/RTL_SOURCE_FILES/CORE_RTL/zilla_instruction_memory.sv
$proj_dir/RTL/CORE/RTL_SOURCE_FILES/CORE_RTL/zilla_ld_hazard_detect.sv
$proj_dir/RTL/CORE/RTL_SOURCE_FILES/CORE_RTL/zilla_ld_sd_address_gen.sv
$proj_dir/RTL/CORE/RTL_SOURCE_FILES/CORE_RTL/zilla_wb_mux.sv
$proj_dir/RTL/IP/CSR/RTL_SOURCE_FILES/csr_top.sv
$proj_dir/RTL/IP/CSR/RTL_SOURCE_FILES/csr_read_mux.sv
$proj_dir/RTL/IP/CSR/RTL_SOURCE_FILES/csr_register_file.sv
$proj_dir/RTL/IP/CSR/RTL_SOURCE_FILES/mhpm_counter_top.sv
$proj_dir/RTL/IP/ZIC_MEM_MAP/RTL_SOURCE_FILES/zic_mmr_top.sv
$proj_dir/RTL/IP/ZIC_MEM_MAP/RTL_SOURCE_FILES/zic_mmr_ctrl.sv
$proj_dir/RTL/IP/ZIC_MEM_MAP/RTL_SOURCE_FILES/zic_mmr_op_mux.sv
$proj_dir/RTL/IP/ZIC_MEM_MAP/RTL_SOURCE_FILES/zic_mmr_reg_file.sv
$proj_dir/RTL/IP/INTERRUPT_CONTROL/RTL_SOURCE_FILES/zic_top.sv
$proj_dir/RTL/IP/INTERRUPT_CONTROL/RTL_SOURCE_FILES/interrupt_recieve.sv
$proj_dir/RTL/IP/INTERRUPT_CONTROL/RTL_SOURCE_FILES/priority_resolve.sv
$proj_dir/RTL/IP/INTERRUPT_CONTROL/RTL_SOURCE_FILES/zic_irg.sv
$proj_dir/RTL/IP/INTERRUPT_CONTROL/RTL_SOURCE_FILES/zilla_interrupt_control.sv
$proj_dir/RTL/IP/PROGRAM_CONTROL/RTL_SOURCE_FILES/zpc_top.sv
$proj_dir/RTL/IP/PROGRAM_CONTROL/RTL_SOURCE_FILES/z_exception_detect.sv
$proj_dir/RTL/IP/PROGRAM_CONTROL/RTL_SOURCE_FILES/zilla_instruction_buffer.sv
$proj_dir/RTL/IP/PROGRAM_CONTROL/RTL_SOURCE_FILES/zilla_pc_update.sv
$proj_dir/RTL/IP/PROGRAM_CONTROL/RTL_SOURCE_FILES/zilla_program_control_fsm.sv
$proj_dir/RTL/IP/DEBUG/RTL/apb_slave_dmreg_top.sv
$proj_dir/RTL/IP/DEBUG/RTL/debug_module_fsm.sv
$proj_dir/RTL/IP/DEBUG/RTL/dm_register_file.sv
$proj_dir/RTL/IP/DEBUG/RTL/dm_register_mux.sv
$proj_dir/RTL/IP/DEBUG/RTL/dtm_to_dm.sv
$proj_dir/RTL/IP/DEBUG/RTL/jtag_apb_master_interface.sv
$proj_dir/RTL/IP/JTAG/RTL_SOURCE_CODES/jtag_data_register.sv
$proj_dir/RTL/IP/JTAG/RTL_SOURCE_CODES/jtag_instruction_register.sv
$proj_dir/RTL/IP/JTAG/RTL_SOURCE_CODES/jtag_tap_controller.sv
$proj_dir/RTL/IP/JTAG/RTL_SOURCE_CODES/jtag_tdo_mux.sv
$proj_dir/RTL/IP/JTAG/RTL_SOURCE_CODES/jtag_top.sv
$proj_dir/RTL/IP/APB/RTL_SOURCE_FILES/APB_Master.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/carry_skip_48bit.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/carry_skip_4bit.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/cla_adder_12bit.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/cla_adder_16bit.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/cla_adder_24bit.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/cla_adder_4bit.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/cla_adder_6bit.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/cla_adder_8bit.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/csa_48bit.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/csa_96bit.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/full_adder.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/half_adder.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/multiplier_top.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/vedic_16x16.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/vedic_2x2.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/vedic_32x32.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/vedic_4x4.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/vedic_64x64.sv
$proj_dir/RTL/IP/MULTIPLIER/RTL_SOURCE_FILES/vedic_8x8.sv
$proj_dir/RTL/IP/DIVIDER/RTL_SOURCE_FILES/riscv_divider_32bit.sv
$proj_dir/RTL/IP/DIVIDER/RTL_SOURCE_FILES/riscv_divider_64bit.sv
$proj_dir/RTL/IP/DIVIDER/RTL_SOURCE_FILES/riscv_divider.sv
$proj_dir/RTL/IP/DIVIDER/RTL_SOURCE_FILES/zilla_divider.sv
$proj_dir/RTL/IP/DIVIDER/RTL_SOURCE_FILES/zilla_reminder.sv
$tb_dir/uvme/RISCV_TOP/RISCV_INTERFACES/riscv_intf.svh
$tb_dir/uvme/RISCV_TOP/RISCV_INTERFACES/write_back_interface.svh
$tb_dir/uvme/RISCV_TOP/RISCV_INTERFACES/ldst_out_intf.svh
$tb_dir/uvme/RISCV_TOP/RISCV_PACKAGE/riscv_package.svh
$tb_dir/uvme/RISCV_TOP/riscv_top_tb.svh
